version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3001:3000'  
      - '3002:3000'  
      - '3003:3000'
    external_links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'

networks:
  default:
    name: socket-manager

